databases:
  - name: outbook_DB
    databaseName: outbook_db
    user: outbook
    region: singapore

services:
  - type: web
    name: outbook
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: outbook_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
